Auto download the downloader from the latest release
eisopux/checker-framework-vscode pull request #169
Opened 2023-08-23 16:35 UTC by Ao-senXiong

2023-08-23 17:07 UTC, Ao-senXiong commented
Prof. Dietl, will you make a new release on both checker-framework-languageserver-downloader and checker-framework-languageserver? I seem do not have permission to do it in this org. Otherwise, please grant me the write permission to the repo.

2023-08-23 21:04 UTC, wmdietl requested changes
Nice!
I see a few mentions of the old downloader jar file, e.g. here https://github.com/eisopux/checker-framework-vscode/blob/0ee64c5af51a8c43384312b10559512a8f844734/src/extension.ts#L103
Please do a search for it throughout, including the build instructions.

I'm wondering whether lower-case `download-downloader.sh` would be better. Or `get-downloader-release.sh`?

2023-08-23 21:10 UTC, Ao-senXiong commented
> Nice! I see a few mentions of the old downloader jar file, e.g. here
> 
> https://github.com/eisopux/checker-framework-vscode/blob/0ee64c5af51a8c43384312b10559512a8f844734/src/extension.ts#L103
> 
> 
> Please do a search for it throughout, including the build instructions.
> I'm wondering whether lower-case `download-downloader.sh` would be better. Or `get-downloader-release.sh`?

Thanks, I will take get-downloader-release.sh. Do you want me to also update all version numbers from 0.2 to 0.3? Or you will do it when you make a new release?

2023-08-23 21:12 UTC, wmdietl commented
> Thanks, I will take get-downloader-release.sh. Do you want me to also update all version numbers from 0.2 to 0.3? Or you will do it when you make a new release?

Ideally, we'll have only one place where we update the release number. If you see a way to do that, please make a PR for that. Otherwise, I'll do it with a release.

2023-08-23 21:16 UTC, Ao-senXiong commented
> 

Ok, before you publish the extension in the vscode marketplace, I can try to test it after the new release of the downloader and language server. Just double check it is working.

2023-08-24 08:03 UTC, wmdietl approved these changes
Thanks!

2023-08-24 08:03 UTC, wmdietl commented on package.json
> +    "download-downloader": "./scripts/get-downloader-release.sh",
```suggestion
    "vscode:prepublish": "npm run compile; npm run get-downloader-release",
    "get-downloader-release": "./scripts/get-downloader-release.sh",
```

2023-08-24 08:11 UTC, merged